/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardItemsIndexRouteImport } from './routes/dashboard/items/index'
import { Route as DashboardImportIndexRouteImport } from './routes/dashboard/import/index'
import { Route as DashboardDiscoverIndexRouteImport } from './routes/dashboard/discover/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardItemsItemIdIndexRouteImport } from './routes/dashboard/items/$itemId/index'
import { Route as ApiAiSummaryIndexRouteImport } from './routes/api/ai/summary/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardItemsIndexRoute = DashboardItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportIndexRoute = DashboardImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverIndexRoute = DashboardDiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardItemsItemIdIndexRoute =
  DashboardItemsItemIdIndexRouteImport.update({
    id: '/items/$itemId/',
    path: '/items/$itemId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiAiSummaryIndexRoute = ApiAiSummaryIndexRouteImport.update({
  id: '/api/ai/summary/',
  path: '/api/ai/summary/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/dashboard/discover/': typeof DashboardDiscoverIndexRoute
  '/dashboard/import/': typeof DashboardImportIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
  '/api/ai/summary/': typeof ApiAiSummaryIndexRoute
  '/dashboard/items/$itemId/': typeof DashboardItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/dashboard/discover': typeof DashboardDiscoverIndexRoute
  '/dashboard/import': typeof DashboardImportIndexRoute
  '/dashboard/items': typeof DashboardItemsIndexRoute
  '/api/ai/summary': typeof ApiAiSummaryIndexRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/dashboard/discover/': typeof DashboardDiscoverIndexRoute
  '/dashboard/import/': typeof DashboardImportIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
  '/api/ai/summary/': typeof ApiAiSummaryIndexRoute
  '/dashboard/items/$itemId/': typeof DashboardItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/api/auth/$'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/discover/'
    | '/dashboard/import/'
    | '/dashboard/items/'
    | '/api/ai/summary/'
    | '/dashboard/items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/items'
    | '/api/ai/summary'
    | '/dashboard/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/dashboard/'
    | '/api/auth/$'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/dashboard/discover/'
    | '/dashboard/import/'
    | '/dashboard/items/'
    | '/api/ai/summary/'
    | '/dashboard/items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAiSummaryIndexRoute: typeof ApiAiSummaryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/items/': {
      id: '/dashboard/items/'
      path: '/items'
      fullPath: '/dashboard/items/'
      preLoaderRoute: typeof DashboardItemsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import/': {
      id: '/dashboard/import/'
      path: '/import'
      fullPath: '/dashboard/import/'
      preLoaderRoute: typeof DashboardImportIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/discover/': {
      id: '/dashboard/discover/'
      path: '/discover'
      fullPath: '/dashboard/discover/'
      preLoaderRoute: typeof DashboardDiscoverIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/items/$itemId/': {
      id: '/dashboard/items/$itemId/'
      path: '/items/$itemId'
      fullPath: '/dashboard/items/$itemId/'
      preLoaderRoute: typeof DashboardItemsItemIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/ai/summary/': {
      id: '/api/ai/summary/'
      path: '/api/ai/summary'
      fullPath: '/api/ai/summary/'
      preLoaderRoute: typeof ApiAiSummaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDiscoverIndexRoute: typeof DashboardDiscoverIndexRoute
  DashboardImportIndexRoute: typeof DashboardImportIndexRoute
  DashboardItemsIndexRoute: typeof DashboardItemsIndexRoute
  DashboardItemsItemIdIndexRoute: typeof DashboardItemsItemIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDiscoverIndexRoute: DashboardDiscoverIndexRoute,
  DashboardImportIndexRoute: DashboardImportIndexRoute,
  DashboardItemsIndexRoute: DashboardItemsIndexRoute,
  DashboardItemsItemIdIndexRoute: DashboardItemsItemIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAiSummaryIndexRoute: ApiAiSummaryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
